import asyncio
import pandas as pd
import json
import os

# Import the visual analyzer directly
from analytics.analyzer_v2 import generate_visual_summary

async def main():
    print("Initializing test data...")
    
    # 1. Create a small assumed dataframe
    data = [
        {"Department": "IT", "Amount": 5000, "Date": "2023-01-01"},
        {"Department": "HR", "Amount": 1500, "Date": "2023-01-02"},
        {"Department": "Engineering", "Amount": 12000, "Date": "2023-01-03"},
        {"Department": "IT", "Amount": 3000, "Date": "2023-01-04"},
        {"Department": "Sales", "Amount": 8000, "Date": "2023-01-05"}
    ]
    df = pd.DataFrame(data)
    
    query = "Show me the total amount spent per department in a bar chart"
    
    print(f"Testing visual pipeline with query: '{query}'...")
    print("Waiting for Gemini to generate the Vega description...")
    
    # 2. Call analyzer_v2 to test AI capability
    result = await generate_visual_summary(df, query)
    
    if result.get("status") == "error":
        print("\n❌ Pipeline Error:")
        print(result.get("content"))
        return
        
    vega_spec = result.get("vega_spec", {})
    
    # 3. Inject the data into the vega spec so it renders standalone
    # (The AI typically leaves data empty for the frontend to inject)
    if "data" not in vega_spec or not vega_spec["data"].get("values"):
        vega_spec["data"] = {"values": result.get("data", [])}
        
    # 4. Generate the HTML file to test frontend rendering reliability
    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
      <title>Vega-Lite Rendering Test</title>
      <!-- Load Vega dependencies -->
      <script src="https://cdn.jsdelivr.net/npm/vega@5"></script>
      <script src="https://cdn.jsdelivr.net/npm/vega-lite@5"></script>
      <script src="https://cdn.jsdelivr.net/npm/vega-embed@6"></script>
      <style>
        body {{ font-family: sans-serif; padding: 40px; background: #1e1e1e; color: white; }}
        #vis {{ margin-top: 20px; background: rgba(255,255,255,0.05); padding: 20px; border-radius: 8px; min-height: 400px; }}
      </style>
    </head>
    <body>
      <h2>Testing Pipeline Reliability</h2>
      <p><strong>Query:</strong> {query}</p>
      <p><strong>AI Status:</strong> Success</p>
      
      <!-- The container for our chart -->
      <div id="vis"></div>
      
      <script>
        // The exact Vega spec generated by analyzer_v2.py
        const spec = {json.dumps(vega_spec)};
        
        // Render it just like the React frontend does
        vegaEmbed('#vis', spec, {{theme: 'dark'}})
            .then(result => console.log("Chart rendered successfully!"))
            .catch(error => {{
                console.error("Chart failed to render:", error);
                document.getElementById('vis').innerHTML = "<p style='color: red;'>Vega-Lite Render Error: " + error.message + "</p>";
            }});
      </script>
    </body>
    </html>
    """
    
    html_path = os.path.join(os.path.dirname(__file__), "test_chart.html")
    with open(html_path, "w", encoding="utf-8") as f:
        f.write(html_content)
        
    print(f"\n✅ Success! Gemini successfully generated the Vega spec.")
    print(f"The rendered chart has been saved to: {html_path}")
    print("Double-click this HTML file to view the plot in your browser!")

if __name__ == "__main__":
    asyncio.run(main())
